// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5tfqDMei1a7RgPeSd8eL106rEF8FiZmU',
    appId: '1:1041630790571:web:7708fee394343121e1c8ee',
    messagingSenderId: '1041630790571',
    projectId: 'messenger-32a83',
    authDomain: 'messenger-32a83.firebaseapp.com',
    storageBucket: 'messenger-32a83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR7Nn0NBJrjUA5NdhxzyMjxJzaaVgXJFo',
    appId: '1:1041630790571:android:6ec0749c4654ea0fe1c8ee',
    messagingSenderId: '1041630790571',
    projectId: 'messenger-32a83',
    storageBucket: 'messenger-32a83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Ee46k5rrHTOYI0kFsZ_nDmaV9reGuA4',
    appId: '1:1041630790571:ios:eea5bb51fdf5caf1e1c8ee',
    messagingSenderId: '1041630790571',
    projectId: 'messenger-32a83',
    storageBucket: 'messenger-32a83.appspot.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Ee46k5rrHTOYI0kFsZ_nDmaV9reGuA4',
    appId: '1:1041630790571:ios:5aafbc6d9873a2d0e1c8ee',
    messagingSenderId: '1041630790571',
    projectId: 'messenger-32a83',
    storageBucket: 'messenger-32a83.appspot.com',
    iosBundleId: 'com.example.messenger.RunnerTests',
  );
}
